### PR TITLE
Rybkin Konstantin, M3238

### PR DESCRIPTION
**Pull request by rbkn99**

### CODE REVIEW

**Comment by ubique** [comment]
Не работает:

$ ./os-find /tmp -nlinks 2
Usage:
	os-find <absolute_path> <-inum num> <-name name> <-size [-=+]size> <-nlinks num> <-exec absolute_path>

Exception occurred during the file walking:
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ


Ожидается, что ошибки по пути не будут приводить к остановке выполнения всей программы.

**Comment by rbkn99** [comment]
fixed

**Comment by ubique** [comment]
Не работает:

$ ./os-find /tmp  -nlinks 2  
Usage:
	os-find <absolute_path> <-inum num> <-name name> <-size [-=+]size> <-nlinks num> <-exec absolute_path>

Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-fwupd.service-QZIskJ
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-resolved.service-6GDx3U
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-upower.service-I29TaI
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-ModemManager.service-2A5KDE
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-colord.service-CyuKFu
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-tor@default.service-WCwnsx
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-apache2.service-aLNu5E
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-timesyncd.service-Ir9HML
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-bolt.service-QfXLHF
/tmp/2
/tmp/1
$ ./os-find /tmp  -nlinks 2  -exec /usr/bin/md5sum
Usage:
	os-find <absolute_path> <-inum num> <-name name> <-size [-=+]size> <-nlinks num> <-exec absolute_path>

Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-fwupd.service-QZIskJ
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-resolved.service-6GDx3U
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-upower.service-I29TaI
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-ModemManager.service-2A5KDE
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-colord.service-CyuKFu
program finished with -1 code.
Bad address
execution finished with 1 code.
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-tor@default.service-WCwnsx
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-apache2.service-aLNu5E
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-timesyncd.service-Ir9HML
program finished with -1 code.
Bad address
execution finished with 1 code.
Cannot open directory: /tmp/systemd-private-d0071278a727402580037461864fbbf1-bolt.service-QfXLHF
/tmp/2
/tmp/1

**Comment by rbkn99** [comment]
fix (надеюсь, что последний)

**Comment by ubique** [comment]
Зачтено.

**Pull request closed without merging**
