### PR TITLE
Нагдалян Арсен, M3234

### PR DESCRIPTION
**Pull request by ArsenHD**

### CODE REVIEW

**Comment by ubique** [comment]
Плохое поведение:

$ ./find 
Segmentation fault (core dumped)

**Comment by ArsenHD** [comment]
Fixed

**Comment by ubique** [comment]
Плохое поведение:

$ ./find  /tmp
Error: invalid arguments
$ ./find  /tmp -name 1
Segmentation fault (core dumped)

**Comment by ArsenHD** [comment]
FIxed

**Comment by ubique** [comment]
Не работает:

$ ./find /tmp  -inum 262179 -nlinks 2  -name 2 -exec /usr/bin/md5sum
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-fwupd.service-QZIskJ
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-resolved.service-6GDx3U
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-upower.service-I29TaI
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-ModemManager.service-2A5KDE
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-colord.service-CyuKFu
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-tor@default.service-WCwnsx
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-apache2.service-aLNu5E
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-timesyncd.service-Ir9HML
Error opening directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-bolt.service-QfXLHF
execve: Bad address
munmap_chunk(): invalid pointer

**Comment by ArsenHD** [comment]
Fixed

**Comment by ubique** [comment]
Зачтено.

**Pull request closed without merging**
