### PR TITLE
Artem Ustinov, M3238

### PR DESCRIPTION
**Pull request by yosabaki**

### CODE REVIEW

**Comment by ubique** [comment]
Не работает:

$ stat -c "%h" /tmp/2
2
$ stat -c "%h" /tmp/1
2
$ stat -c "%h" /tmp/2
2
$ ./find /tmp/ -nlinks 2 2>/dev/null
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-fwupd.service-QZIskJ
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-systemd-resolved.service-6GDx3U
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-upower.service-I29TaI
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-ModemManager.service-2A5KDE
/tmp//photo_2019-04-29_01-01-20.jpg
/tmp//.X1024-lock
/tmp//empty
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-colord.service-CyuKFu
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-tor@default.service-WCwnsx
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-apache2.service-aLNu5E
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-systemd-timesyncd.service-Ir9HML
/tmp//config-err-iTPBHm
Can't access directory /tmp//systemd-private-d0071278a727402580037461864fbbf1-bolt.service-QfXLHF

**Comment by yosabaki** [comment]
:( Если ввести /tmp вместо /tmp/, то работало бы. Но я исправил.

**Comment by ubique** [comment]
1. Утекает ресурс открытой директории.
2. Не работает:

$ ./find  /tmp -nlinks 2  -inum 262179  
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-rtkit-daemon.service-ccJxIZ
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-fwupd.service-QZIskJ
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-resolved.service-6GDx3U
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-upower.service-I29TaI
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-ModemManager.service-2A5KDE
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-colord.service-CyuKFu
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-tor@default.service-WCwnsx
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-apache2.service-aLNu5E
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-systemd-timesyncd.service-Ir9HML
Can't access directory /tmp/systemd-private-d0071278a727402580037461864fbbf1-bolt.service-QfXLHF
$ stat /tmp/2
  File: /tmp/2
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd01h/64769d	Inode: 262179      Links: 2
Access: (0644/-rw-r--r--)  Uid: ( 1000/ amnesia)   Gid: ( 1000/ amnesia)
Access: 2019-05-04 15:31:19.095401306 +0300
Modify: 2019-05-01 20:06:47.544662515 +0300
Change: 2019-05-01 20:06:48.980663202 +0300
 Birth: -
$

**Comment by yosabaki** [comment]
Теперь точно исправил

**Comment by ubique** [comment]
Зачтено.

**Pull request closed without merging**
